config/routes.rb
CuboLedsproyect::Application.routes.draw do
  get "memoria/index"
  get "personal/new"
  get "personal/create"
  resources :contactos
  resources :videeoos
  resources :imagenes

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/imagene.rb
class Imagene < ActiveRecord::Base
  resourcify
  mount_uploader :image, ImageUploader
end

app/controllers/imagenes_controller.rb
class ImagenesController < ApplicationController
  before_action :set_imagene, only: [:show, :edit, :update, :destroy]

  # GET /imagenes
  # GET /imagenes.json
  def index
    @imagenes = Imagene.all
  end

  # GET /imagenes/1
  # GET /imagenes/1.json
  def show
  end

  # GET /imagenes/new
  def new
    @imagene = Imagene.new
  end

  # GET /imagenes/1/edit
  def edit
  end

  # POST /imagenes
  # POST /imagenes.json
  def create
    @imagene = Imagene.new(imagene_params)

    respond_to do |format|
      if @imagene.save
        format.html { redirect_to @imagene, notice: 'Imagene was successfully created.' }
        format.json { render action: 'show', status: :created, location: @imagene }
      else
        format.html { render action: 'new' }
        format.json { render json: @imagene.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /imagenes/1
  # PATCH/PUT /imagenes/1.json
  def update
    respond_to do |format|
      if @imagene.update(imagene_params)
        format.html { redirect_to @imagene, notice: 'Imagene was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @imagene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imagenes/1
  # DELETE /imagenes/1.json
  def destroy
    @imagene.destroy
    respond_to do |format|
      format.html { redirect_to imagenes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imagene
      @imagene = Imagene.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imagene_params
      params.require(:imagene).permit(:texto, :description, :image)
    end
end

app/helpers/imagenes_helper.rb
module ImagenesHelper
end

app/views/imagenes/_form.html.erb
<div class="container">
	<%= simple_form_for(@imagene) do |f| %>
	  <%= f.error_notification %>

	  <div class="form-inputs">
	    <%= f.input :texto %>
	    <%= f.input :description %>
	    <%= f.file_field :image %>
	  </div>

	  <div class="form-actions">
	    <%= f.button :submit %>
	  </div>
	<% end %>
</div>

app/views/imagenes/edit.html.erb
<div class="container">
	<h1>Editing imagene</h1>

	<%= render 'form' %>

	<%= link_to 'Back', imagenes_path %>
</div>

app/views/imagenes/new.html.erb
<h1>New imagene</h1>

<%= render 'form' %>

<%= link_to 'Back', imagenes_path %>

app/views/imagenes/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<%= image_tag @imagene.image , size: "800" %>

	<p>
	  <strong>Texto:</strong>
	  <%= @imagene.texto %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @imagene.description %>
	</p>

	<%= link_to 'Edit', edit_imagene_path(@imagene) %> |
	<%= link_to 'Back', imagenes_path %>
</div>