config/routes.rb
CuboLedsproyect::Application.routes.draw do
  get "memoria/index"
  get "personal/new"
  get "personal/create"
  resources :contactos
  resources :videeoos
  resources :imagenes

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/videeoo.rb
class Videeoo < ActiveRecord::Base
end

app/controllers/videeoos_controller.rb
class VideeoosController < ApplicationController
  before_action :set_videeoo, only: [:show, :edit, :update, :destroy]

  # GET /videeoos
  # GET /videeoos.json
  def index
    @videeoos = Videeoo.all
  end

  # GET /videeoos/1
  # GET /videeoos/1.json
  def show
  end

  # GET /videeoos/new
  def new
    @videeoo = Videeoo.new
  end

  # GET /videeoos/1/edit
  def edit
  end

  # POST /videeoos
  # POST /videeoos.json
  def create
    @videeoo = Videeoo.new(videeoo_params)

    respond_to do |format|
      if @videeoo.save
        format.html { redirect_to @videeoo, notice: 'Videeoo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @videeoo }
      else
        format.html { render action: 'new' }
        format.json { render json: @videeoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videeoos/1
  # PATCH/PUT /videeoos/1.json
  def update
    respond_to do |format|
      if @videeoo.update(videeoo_params)
        format.html { redirect_to @videeoo, notice: 'Videeoo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @videeoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videeoos/1
  # DELETE /videeoos/1.json
  def destroy
    @videeoo.destroy
    respond_to do |format|
      format.html { redirect_to videeoos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_videeoo
      @videeoo = Videeoo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def videeoo_params
      params.require(:videeoo).permit(:Titulo, :Descripcion, :Url, :Subido_por)
    end
end

app/helpers/videeoos_helper.rb
module VideeoosHelper
end

app/views/videeoos/_form.html.erb
<div class="container">
  <%= simple_form_for(@videeoo) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :Titulo %>
      <%= f.input :Descripcion %>
      <%= f.input :Url %>
      <p style="font-size:7pt;"> 
        <i>
           Ejemplo: https://www.youtube.com/watch?v=<strong>QweFe4CeAJg</strong> </br>
           Poner solo: <strong>QweFe4CeAJg<strong>
        </i>
      </p>

      <%= f.input :Subido_por %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/videeoos/edit.html.erb
<div class="container">
	<h1>Editar Video</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @videeoo %> |
	<%= link_to 'Back', videeoos_path %>
</div>

app/views/videeoos/index.html.erb
      <h1 class="container"><strong>Videos</strong></h1>

      <% @videeoos.each do |videeoo| %>
        <div class="container">
          <div class="row featurette">
            <div class="col-md-7">
                <iframe width="645px" height="345px"
                        src="http://www.youtube.com/embed/<%=videeoo.Url%>"
                        frameborder="1">
                </iframe>
            </div>
            <div class="col-md-5 ">
                <p class="vid-titulo"><%=videeoo.Titulo%></p>
                <h3><strong>Descripcion <i class="fa fa-comment-o"></i></strong></h3>
                <p class="video-cont" style="text-align:center; height:200px;"><%=videeoo.Descripcion%></p>
                <h3><strong>Subido por:</strong></h3>
                <p style="text-align:right;"><%=videeoo.Subido_por%></p>
            </div>
          </div>
          <div>
                <td><%= link_to 'Show', videeoo %></td>
                <% if can? :create, Videeoo %>
                  <td><%= link_to 'Edit', edit_videeoo_path(videeoo) %></td>
                <%end%>
                <% if can? :delete, Videeoo %>
                  <td><%= link_to 'Destroy', videeoo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <%end%>
          </div>
          <hr class="featurette-divider">
        </div>
    <% end %>

</br>

<% if can? :create, Videeoo %>
  <%= link_to 'New Video', new_videeoo_path %>
<%end%>

app/views/videeoos/new.html.erb
<h1>New videeoo</h1>

<%= render 'form' %>

<%= link_to 'Back', videeoos_path %>

app/views/videeoos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
	<div class="col-md-12" style="text-align:center; margin-top:20px;">
	<iframe align="middle" width="860px" height="515px" src="http://www.youtube.com/embed/<%= @videeoo.Url %>"                       frameborder="1">
	</iframe>
	</div>

	<p>
	  <strong>Titulo:</strong>
	  <%= @videeoo.Titulo %>
	</p>

	<p>
	  <strong>Descripcion:</strong>
	  <%= @videeoo.Descripcion %>
	</p>

	<p>
	  <strong>Subido por:</strong>
	  <%= @videeoo.Subido_por %>
	</p>

	<%= link_to 'Edit', edit_videeoo_path(@videeoo) %> |
	<%= link_to 'Back', videeoos_path %>

</div>