config/routes.rb
CuboLedsproyect::Application.routes.draw do
  get "memoria/index"
  get "personal/new"
  get "personal/create"
  resources :contactos
  resources :videeoos
  resources :imagenes

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
      else
      can :read, :all
    end

    if user.has_role? :equipoproyecto
      can :delete, :all
      can :create, :all
    end


    if user.has_role? :gestorcontenidos
      can :create, :all
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
end

app/models/imagene.rb
class Imagene < ActiveRecord::Base
  resourcify
  mount_uploader :image, ImageUploader
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :Nombre, :Email, :Asunto, :Body

  validates :Nombre, :Email, :Asunto, :Body, :presence => true
  validates :Email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/videeoo.rb
class Videeoo < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/imagenes_controller.rb
class ImagenesController < ApplicationController
  before_action :set_imagene, only: [:show, :edit, :update, :destroy]

  # GET /imagenes
  # GET /imagenes.json
  def index
    @imagenes = Imagene.all
  end

  # GET /imagenes/1
  # GET /imagenes/1.json
  def show
  end

  # GET /imagenes/new
  def new
    @imagene = Imagene.new
  end

  # GET /imagenes/1/edit
  def edit
  end

  # POST /imagenes
  # POST /imagenes.json
  def create
    @imagene = Imagene.new(imagene_params)

    respond_to do |format|
      if @imagene.save
        format.html { redirect_to @imagene, notice: 'Imagene was successfully created.' }
        format.json { render action: 'show', status: :created, location: @imagene }
      else
        format.html { render action: 'new' }
        format.json { render json: @imagene.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /imagenes/1
  # PATCH/PUT /imagenes/1.json
  def update
    respond_to do |format|
      if @imagene.update(imagene_params)
        format.html { redirect_to @imagene, notice: 'Imagene was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @imagene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imagenes/1
  # DELETE /imagenes/1.json
  def destroy
    @imagene.destroy
    respond_to do |format|
      format.html { redirect_to imagenes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imagene
      @imagene = Imagene.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imagene_params
      params.require(:imagene).permit(:texto, :description, :image)
    end
end

app/controllers/memoria_controller.rb
class MemoriaController < ApplicationController
  def index
  end
end

app/controllers/personal_controller.rb
class PersonalController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes!(user_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  private
  def user_params
    params.require(:user).permit!
  end
end

app/controllers/videeoos_controller.rb
class VideeoosController < ApplicationController
  before_action :set_videeoo, only: [:show, :edit, :update, :destroy]

  # GET /videeoos
  # GET /videeoos.json
  def index
    @videeoos = Videeoo.all
  end

  # GET /videeoos/1
  # GET /videeoos/1.json
  def show
  end

  # GET /videeoos/new
  def new
    @videeoo = Videeoo.new
  end

  # GET /videeoos/1/edit
  def edit
  end

  # POST /videeoos
  # POST /videeoos.json
  def create
    @videeoo = Videeoo.new(videeoo_params)

    respond_to do |format|
      if @videeoo.save
        format.html { redirect_to @videeoo, notice: 'Videeoo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @videeoo }
      else
        format.html { render action: 'new' }
        format.json { render json: @videeoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videeoos/1
  # PATCH/PUT /videeoos/1.json
  def update
    respond_to do |format|
      if @videeoo.update(videeoo_params)
        format.html { redirect_to @videeoo, notice: 'Videeoo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @videeoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videeoos/1
  # DELETE /videeoos/1.json
  def destroy
    @videeoo.destroy
    respond_to do |format|
      format.html { redirect_to videeoos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_videeoo
      @videeoo = Videeoo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def videeoo_params
      params.require(:videeoo).permit(:Titulo, :Descripcion, :Url, :Subido_por)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/imagenes_helper.rb
module ImagenesHelper
end

app/helpers/memoria_helper.rb
module MemoriaHelper
end

app/helpers/personal_helper.rb
module PersonalHelper
end

app/helpers/videeoos_helper.rb
module VideeoosHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_messages_navegador.html.erb
<div class="container" style="margin-top:30px;">
	<div class="col-md-5">
		<div style="float: left; margin: 5px; height:40px; width:40px; padding-top:5px;">
			<%=image_tag ("logo.png")%>			
		</div>

		<span style="font-size:14pt;padding-left:10px;">Proyecto <span class="fa fa-code-fork fa-1x" data-content="Este es un proyecto desarrollado para Modulo superior de Desarrollo de Aplicaciones Multiplataforma del colegio Santo Domingo Savio de Madrid. Promoción 2013-1014"></span></span>
		<h1>Cubo de LED's</h1>
	</div>

	<div class="col-md-7" style="text-align:right;padding-right:100px;font-size:24pt;">
		<a href="https://www.youtube.com/watch?v=ZBxHqHhS8Jw"  data-info="You Tube"><i class="fa fa-youtube-square "></i></a>
		<a href="https://github.com/dmorenodev/Cubo-Leds-proyects"  data-info="Git Hub"><i class="fa fa-github-square "></i></a>
		<a href="https://bitbucket.org/proyectocuboled/cubeled/src" data-info="Bitbuket"><i class="fa fa-bitbucket"></i></a>
		<a href="https://twitter.com/da17mo" data-info="Twitter"><i class="fa fa-twitter"></i></a>
	</div>

</div>

app/views/layouts/_messages_registro_inicio.html.erb
<div class="authform">
	<%= button_to "Iniciar sesión", new_user_session_path, :class => 'button' %>
	<%= button_to "Registrarse", new_user_registration_path, :class => 'button' %>
</div>

app/views/layouts/_navigation.html.erb
    <div class="container">
        <%= render 'layouts/messages_navegador'%>
      <div id="tab" class="tabs">
        <nav style="border-bottom:3px solid #BECBD2;">
          <ul>
            <li><a><%= link_to 'Inicio', root_path, class: 'fa fa-archive'%></a></li>
            <li><a><%= link_to 'Memoria', imagenes_path, class: 'fa fa-book' %></a></li>
            <li><a><%= link_to 'Imagenes', memoria_index_path, class: 'fa fa-picture-o'%></a></li>
            <li><a id="video"><%= link_to 'Videos', videeoos_path, class: 'fa fa-video-camera tab-current' %></a></li>
            <li><%= link_to 'Contacto', new_contacto_path, class: 'fa fa-phone' %></li>
            <li><%= link_to 'Area personal',personal_new_path, class: 'fa fa-align-justify' %></li>

          </ul>
        </nav>
      </div>
    </div>

app/views/layouts/_navigation_links.html.erb
    <% if user_signed_in? %>
        <div class=" sidebar">
	          <ul class="nav nav-sidebar">
	            <li><p>Hola <strong> <%= current_user.name %> </strong>.</p></li>
		            <% if can? :manage, User %>
					 	<li><%= link_to 'Gestor de usuarios', users_path %></li>
					<% end %>
	            <li><%= link_to 'Editar cuenta', edit_user_registration_path %></li>
	            <li role="presentation" class="divider"></li>
	            <li><%= link_to 'Cerrar sesión', destroy_user_session_path, :method=>'delete' %></li>
	          </ul>
        </div>
	<% else %>
		<%= render 'layouts/messages_registro_inicio'%>
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="Desarrolla tu propio cubo de led, Intrucciones de como hacerlo, soporte, te ayudamos en todos. Programas incluidos C# Arduino Efectos incluidos">

    <meta name="keywords" content="proyecto moreno hub curriculum git cubo led ramon este hay">

    <meta name="author" content="David Moreno Moreno">

   


    <title><%= content_for?(:title) ? yield(:title) : "Cubo Leds 8x8x8 Arduino C# " %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Cubo Leds" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
     <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

     <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
     
     <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51242265-1', 'cubeledproyect.com');
  ga('send', 'pageview');

</script>

  </head>
  <body>

    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>